### PR TITLE
Libvpx issue

### PR DESCRIPTION
**Pull request by Chuongv**
So I feel like we are getting closer to getting libvpx into this. If you allow warnings, it passes :smile: but I don't think that's what we want. Hopefully you can take a look @dvor

### CODE REVIEW

**Comment by dvor** [comment]
Those warning are from libsodium and toxcore. They were here before. :grinning: 

Looks good :+1:

**Comment by dvor** [comment]
libopus 1.1 works for me now, can you update it in podspec? I'll merge this pull request then.

**Comment by Chuongv** [comment]
Should I bump up the toxcore version while I am at it?

**Comment by dvor** [comment]
Yes, you can.

**Comment by Chuongv** [comment]
Done!

**Comment by dvor** [comment]
Cool!

**Comment by dvor** [comment]
@Chuongv I've pushed 0.1.4 to the CocoaPods repository

**Pull request merged**
